# Use the official .NET SDK image as the base image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-new

# Set the working directory to /app
WORKDIR /appfrontend

# Copy the solution file and restore dependencies
COPY BikeRental.Frontend.sln .
COPY BikeRental.Frontend/BikeRental.Frontend.csproj ./BikeRental.Frontend/
COPY BikeRental.Frontend/BikeRental.Frontend.csproj.user ./BikeRental.Frontend/

# Restore NuGet packages
RUN dotnet restore

# Copy the rest of the application code
COPY BikeRental.Frontend/. ./BikeRental.Frontend/

# Build the application
RUN dotnet build -c Release -o out

# Create the runtime image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-final
WORKDIR WORKDIR /appfrontend
COPY --from=build-new /appfrontend/out .

# Expose port 80 for the application
EXPOSE 80

# Specify the entry point for the application
ENTRYPOINT ["dotnet", "BikeRental.Frontend.dll"]