version: '3.4'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BikeRental!1"
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - ./db-backup:/var/opt/mssql/backup
  
  backend-api:
    container_name: backend-api
    environment:
      ASPNETCORE_URLS: "http://+8080"
    build: .
    ports:
      - "8080:80"
    depends_on:
      - ms-sql-server
  frontend-app:
    container_name: fronend-app
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORT: "https://+:8081"
      ASPNETCORE_URLS: "http://+8080"
    build:
      context: ./BikeRental.Frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"